version: '3.4'

networks:
  universityapi-dev:
    driver: bridge

services:
  universityapi:
    image: universityapi:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      ConnectionCS: "host=postgres_image;port=5432;database=universitysystemdb;username=postgres;password=qwert123"
    networks:
      - universityapi-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwert123"
      POSTGRES_DB: "universitysystemdb"
    networks:
      - universityapi-dev
  
      